<a href="https://colab.research.google.com/github/Luke-Dev-Tech/PytorchNotebooks/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Permute of the tensor

*   List item
*   List item



torch. rand() generates numbers evenly spread between 0 and 1 . torch. randn() generates numbers based on the bell curve, centered at 0 with most values falling between -3 and 3

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x_randn = torch.randn(size=(224,224,3))
print("x with randn ==> ", x_randn)
print("===================================")

x = torch.rand(2,10,2)
print("===================================")
print('x with rand ==> ',x)

x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]
x_original.shape
print("===================================")
print("x with rand and size parameter ==> ",x_original)
print(type(x_original))


x with randn ==>  tensor([[[-1.3847, -0.8712, -0.2234],
         [ 1.7174,  0.3189, -0.4245],
         [ 0.3057, -0.7746, -1.5576],
         ...,
         [ 1.5419, -0.1087, -0.4189],
         [ 1.4384, -0.7068, -1.2520],
         [ 3.0250,  1.3463,  0.8556]],

        [[ 0.3220,  0.4461,  1.5230],
         [ 1.2805, -0.1162,  1.3705],
         [-0.4809, -0.9904, -1.3642],
         ...,
         [-0.2433, -0.2937, -0.6287],
         [-0.0423, -0.2700,  1.4388],
         [ 0.0326, -0.5480, -0.4937]],

        [[ 2.8819, -1.1672,  1.9413],
         [-1.1636, -1.5967,  0.0832],
         [-0.9222, -0.3711, -0.9714],
         ...,
         [ 1.9290, -0.1768,  0.6398],
         [ 0.6913,  0.5199, -0.7546],
         [-0.0334, -0.8276, -0.3524]],

        ...,

        [[-0.6816,  1.7890, -0.2004],
         [ 0.5425,  0.1184,  0.6456],
         [ 0.7943, -1.5064, -0.2336],
         ...,
         [-0.4227, -1.1818,  0.8194],
         [-1.4442,  0.8536,  1.6268],
         [-0.9780, -0.1199,  0.0

In [ ]:
x_permuted = torch.permute(x_original, (2, 0, 1))

In [ ]:
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (Selecting data from tensors)

Indexing

In [ ]:
x = torch.arange(1,10,2)
print(x)

tensor([1, 3, 5, 7, 9])


In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
# you can use ":" to select "all" of a target dimention

x[:, 0, 0]

print(x[0,:,2])

tensor([3, 6, 9])


In [ ]:
x = torch.arange(0,20).reshape(2,5,2)
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]])

In [ ]:
x[:, 0] # this select every page

tensor([[ 0,  1],
        [10, 11]])

In [ ]:
# you want all the 1 index of every row
x[0, :, 1]

tensor([1, 3, 5, 7, 9])

# Pytorch tensors and NumPy


Numpy is a popular scientific Python numerical computing library and because of this, Pythorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'


Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor

import torch
import numpy as np


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when numpy --> pytorch (it reflects numpy's float64)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1.0, 8.0).dtype # pytorch's default is float32

torch.float32

In [ ]:
# let's try changing the array
array = array + 1
array, tensor
# it doesn't change the tensor value

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# torch to numpy

tensor_ones = torch.ones(7)

numpy_tensor = tensor_ones.numpy()
tensor_ones, numpy_tensor

# they reflects each other.

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor_ones = tensor_ones + 1
tensor_ones, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Pytorch Reproducbuility
(Random out of Random)

How neural network learns is
'start with random numbers --> tensor operations --> update random numbers to try and make them better representation of the data -> again --> again ...


To reduce the randomness in the neural networks and Pytorch comes the concpet of **random seed**

In [ ]:
torch.rand(3,3,3)

tensor([[[6.0224e-02, 5.8370e-01, 8.6433e-04],
         [7.5808e-01, 5.8165e-01, 4.3382e-01],
         [3.3265e-02, 3.7463e-01, 7.1104e-01]],

        [[5.9461e-01, 9.4746e-01, 6.2281e-01],
         [7.6846e-02, 7.1221e-01, 3.7273e-01],
         [8.4340e-01, 7.1858e-01, 8.8339e-01]],

        [[2.8271e-01, 5.3121e-01, 5.0577e-01],
         [7.1231e-02, 1.0943e-01, 4.6946e-01],
         [2.5743e-01, 9.8299e-01, 6.7796e-01]]])

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1739, 0.0130, 0.6778, 0.0439],
        [0.4367, 0.4731, 0.9129, 0.0017],
        [0.1279, 0.2028, 0.6808, 0.9808]])
tensor([[0.8409, 0.7430, 0.3531, 0.0833],
        [0.1122, 0.4030, 0.3140, 0.8325],
        [0.2196, 0.6822, 0.8682, 0.9207]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
Random_seed = 42
torch.manual_seed(Random_seed) # .manual seed, works only for one block if you are using a notebook
random_tensor_A = torch.rand(3,4)


torch.manual_seed(Random_seed)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
## Running Tensors and Pytorch objects on the GPUs

In [ ]:
!nvidia-smi

Fri Nov  7 20:20:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   73C    P0             30W /   70W |     120MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access with Pytorch
# CUDA in PyTorch allows your code to run on the GPU instead of the CPU.
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnositic code
# if gpu avaliable use 'cuda' but no avaliable gpu ? fallback to cpu
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count numberof devices
torch.cuda.device_count()

1

In [ ]:
import torch

# Create a tensor on the CPU
x = torch.randn(3, 3)

# Move it to the GPU (if available)
if torch.cuda.is_available():
    tensor_on_gpu = x.to('cuda' )
    print("Tensor is now on GPU:", tensor_on_gpu.device)


Tensor is now on GPU: cuda:0


In [ ]:
x = torch.randn(3, 3, device='cuda')
x

tensor([[ 0.1391, -0.1082, -0.7174],
        [ 0.7566,  0.3715, -1.0049],
        [ 0.0083,  0.3277,  0.2829]], device='cuda:0')

In [ ]:
# Note Tensor only works with CPU
# so moving back to cpu
# but if tensor is on GPU , Can't transform it to NUMPY.

tensor_on_gpu.numpy() # device issue

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the gpu tensor iwht Numpy issue, we can first set it to the CPU.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([[ 0.9579718 ,  1.3221351 ,  0.81718975],
       [-0.7658386 , -0.75062233,  1.3525478 ],
       [ 0.6863219 , -0.32775864,  0.7949687 ]], dtype=float32)